use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :tsheeter, TsheeterWeb.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :tsheeter, TsheeterWeb.Endpoint, server: true

config :tsheeter, Tsheeter.Repo,
  ssl: true,
  show_sensitive_data_on_connection_error: false,
  pool_size: 10

config :libcluster,
  topologies: [
    k8s: [
      strategy: Elixir.Cluster.Strategy.Kubernetes,
      config: [
        kubernetes_node_basename: "tsheeter",
        kubernetes_selector: "app=tsheeter",
        kubernetes_ip_lookup_mode: :pods,
        polling_interval: 3_000
      ]
    ]
  ]

# these are overridden by env vars in releases.exs, but
# need to be defined for `mix compile`
config :tsheeter, :basic_auth,
  username: "",
  password: ""
